# pre-commit.yml

# Add a description for the workflow
name: Pre-commit

# Define the trigger events for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add any additional steps or actions required for the pre-commit checks

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      # Add any additional steps or actions after the pre-commit checks

      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Pre-commit checks"

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
